// Customers actions
// get
export const GET_CUSTOMERS_START = "GET_CUSTOMERS_START";
export const GET_CUSTOMERS_FAILURE = "GET_CUSTOMERS_FAILURE";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
// create
export const CREATE_CUSTOMER_START = "CREATE_CUSTOMER_START";
export const CREATE_CUSTOMER_FAILURE = "CREATE_CUSTOMER_FAILURE";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
// edit
export const EDIT_CUSTOMERS_START = "EDIT_CUSTOMERS_START";
export const EDIT_CUSTOMERS_FAILURE = "EDIT_CUSTOMERS_FAILURE";
export const EDIT_CUSTOMERS_SUCCESS = "EDIT_CUSTOMERS_SUCCESS";
// delete
export const DELETE_CUSTOMERS_START = "DELETE_CUSTOMERS_START";
export const DELETE_CUSTOMERS_FAILURE = "DELETE_CUSTOMERS_FAILURE";
export const DELETE_CUSTOMERS_SUCCESS = "DELETE_CUSTOMERS_SUCCESS";

// Products actions
// get
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
// create
export const CREATE_PRODUCTS_START = "CREATE_PRODUCTS_START";
export const CREATE_PRODUCTS_FAILURE = "CREATE_PRODUCTS_FAILURE";
export const CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS";

// Favorite products actions
// get
export const GET_FAVORITE_PRODUCTS_START = "GET_FAVORITE_PRODUCTS_START";
export const GET_FAVORITE_PRODUCTS_FAILURE = "GET_FAVORITE_PRODUCTS_FAILURE";
export const GET_FAVORITE_PRODUCTS_SUCCESS = "GET_FAVORITE_PRODUCTS_SUCCESS";
// create (add)
export const ADD_FAVORITE_PRODUCT_START = "ADD_FAVORITE_PRODUCT_START";
export const ADD_FAVORITE_PRODUCT_FAILURE = "ADD_FAVORITE_PRODUCT_FAILURE";
export const ADD_FAVORITE_PRODUCT_SUCCESS = "ADD_FAVORITE_PRODUCT_SUCCESS";
// delete
export const DELETE_FAVORITE_PRODUCT_START = "DELETE_FAVORITE_PRODUCT_START";
export const DELETE_FAVORITE_PRODUCT_FAILURE = "DELETE_FAVORITE_PRODUCT_FAILURE";
export const DELETE_FAVORITE_PRODUCT_SUCCESS = "DELETE_FAVORITE_PRODUCT_SUCCESS";
